apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
data:
  access_key: N0s4TlAxU0RSTVRUN1VKTTBPUzE=
  secret_key: azg4QUZ3OUYzQVU4OTNvVEFmdnV3VVJGejkzb3F4WUlFS2lMbTg3VQ==
  host_base: aHR0cHM6Ly9zMy13ZXN0Lm5ycC1uYXV0aWx1cy5pbw==
