# src/arguments.toml

[paths]
data_path = "s3://dfredin/testing/"
data_path_gasf = "s3://dfredin/dataset_gasf/"
models_path = "s3://dfredin/models/"
results_path = "s3://dfredin/results/"

[options]
create_new_gasf = true
apply_snr_filter = false
snr_threshold = 12
shuffle_data = true

select_samples = true
train_model = false
num_bbh = 2000
num_bg = 2000
num_glitch = 2000

[hyperparameters]
learning_rate = 0.0005
epochs = 5
L2_reg = 0.001
batch_size = 1
seed = 55

[ratios]
train = 0.8
test = 0.10
validation = 0.10