# arguments.toml

[paths]
base_path = "../"
data_path = "data/"
results_path = "results/figures/"
models_path = "models/"

[hyperparameters]
learning_rate = 0.0005
epochs = 5
L2_reg = 0.001
batch_size = 32
seed = 55

[ratios]
train = 0.8
test = 0.10
validation = 0.10

[options]
snr_threshold = 12
apply_snr_filter = false
ifos = ["H1", "L1"]
create_new_gasf = false
num_bbh = 3000
num_bg = 3000
num_glitch = 3000
