# arguments.toml

[paths]
base_path = "/home/dfredin/gwgasf/"
data_path = "/home/dfredin/gwgasf/data/"
results_path = "/home/dfredin/gwgasf/results/figures/"
models_path = "/home/dfredin/gwgasf/models/"

[hyperparameters]
learning_rate = 0.0005
epochs = 5
L2_reg = 0.001
batch_size = 32
seed = 55

[ratios]
train = 0.8
test = 0.10
validation = 0.10

[options]
snr_threshold = 12
apply_snr_filter = false
ifos = ["H1", "L1"]
create_new_gasf = false
num_bbh = 2000
num_bg = 2000
num_glitch = 2000
